### ISSUE TITLE
Trims non-alphanumeric letters from GMail account names

### ISSUE THREAD

**Issue by NomdeNet** [judge2020/Battle.net-Switcher#2]
You can use "+" and "." symbols in gmail addresses, to make unique addresses for different services. battlenet switcher seems to trim "+" symbols from the address making it unusable with accounts linked to such emails.

Any chance this can be altered?

**Comment by judge2020** [comment]
i'll look at it

**Comment by tuurbo** [comment]
@NomdeNet Putting curly brackets around the ```+``` character fixed it for me.

eg: ```example+foobar@example.com``` -> ```example{+}foobar@example.com```
